export const ADD_FAQ = 'ADD_FAQ';
export const UPDATE_FAQ = 'UPDATE_FAQ';
export const DELETE_FAQ = 'DELETE_FAQ';
export const GET_FAQS = 'GET_FAQS';
export const GET_EVENT_FAQS = 'GET_EVENT_FAQS';
export const GET_TUTOR_FAQS = 'GET_TUTOR_FAQS';
export const GET_USER_FAQS = 'GET_USER_FAQS';
export const FETCH_BANNERS = 'FETCH_BANNERS';
export const DELETE_BANNER = 'DELETE_BANNER';
export const FETCH_CREDITS = 'FETCH_CREDITS';
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';

export const SELECTED_USER_DATA = 'SELECTED_USER_DATA';
export const RESET_SELECTED_USER_DATA = 'RESET_SELECTED_USER_DATA';
export const DELETE_GALLERY_IMAGE = 'DELETE_GALLERY_IMAGE';
export const FETCH_GALLERY = 'FETCH_GALLERY';
