export const CREATE_EVENT = 'CREATE_EVENT';
export const ADD_SUBEVENT = 'ADD_SUBEVENT';
export const CREATE_SUBEVENT = 'CREATE_SUBEVENT';
export const CREATE_NEW_SUBEVENT = 'CREATE_NEW_SUBEVENT';
export const SELECT_SUBEVENT = 'SELECT_SUBEVENT';
export const UPDATE_SUBEVENT = 'UPDATE_SUBEVENT';
export const CREATE_STAGE = 'CREATE_STAGE';
export const UPDATE_STAGE = 'UPDATE_STAGE';
export const FETCH_COMPETITIONS = 'FETCH_COMPETITIONS';
export const SELECT_COMPETITIONS = 'SELECT_COMPETITIONS';
export const DELETE_COMPETITIONS = 'DELETE_COMPETITIONS';
export const UPDATE_COMPETITIONS = 'UPDATE_COMPETITIONS';
export const FETCH_SKILLS = 'FETCH_SKILLS';
export const REFRESH_COMPETITION = 'REFRESH_COMPETITION';
export const REFRESH_SUBEVENT = 'REFRESH_SUBEVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_SUBEVENT = 'DELETE_SUBEVENT';
export const DELETE_STAGE = 'DELETE_STAGE';
export const RESET_SELECTED_COMPETITION = 'RESET_SELECTED_COMPETITION';
export const GET_COMPETITION_PARTICIPANTS = 'GET_COMPETITION_PARTICIPANTS';

// Sponsers
export const ADD_SPONSOR = 'ADD_SPONSOR';
export const UPDATE_SPONSOR = 'UPDATE_SPONSOR';
export const DELETE_SPONSOR = 'DELETE_SPONSOR';
export const FETCH_SPONSORS = 'FETCH_SPONSORS';
