export const ADD_LEVEL_FILTER = 'ADD_LEVEL_FILTER';
export const FETCH_FILTER_LEVELS = 'FETCH_FILTER_LEVELS';
export const UPDATE_LEVEL_FILTER = 'UPDATE_LEVEL_FILTER';
export const DELETE_LEVEL_FILTER = 'DELETE_LEVEL_FILTER';
