export const FETCH_SKILLS = 'FETCH_SKILLS';
export const CREATE_SKILLS = 'CREATE_SKILLS';
export const UPDATE_SKILLS = 'UPDATE_SKILLS';
export const EDIT_SKILLS = 'EDIT_SKILLS';
export const DELETE_SKILL = 'DELETE_SKILL';

export const GET_SKILL_PARTICIPANTS = 'GET_SKILL_PARTICIPANTS';
export const GET_SKILL_DEMO_PARTICIPANTS = 'GET_SKILL_DEMO_PARTICIPANTS';

export const FETCH_INSTRUCTORS = 'FETCH_INSTRUCTORS';
export const GET_INSTRUCTOR = 'GET_INSTRUCTOR';
export const ADD_INSTRUCTOR = 'ADD_INSTRUCTOR';
export const UPDATE_INSTRUCTOR = 'UPDATE_INSTRUCTOR';
export const DELETE_INSTRUCTOR = 'DELETE_INSTRUCTOR';
