export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_TUTORS = 'FETCH_TUTORS';
export const FETCH_COACHING = 'FETCH_COACHING';

export const RESET_SELECTED_TUTOR = 'RESET_SELECTED_TUTOR';
export const SELECTED_TUTOR = 'SELECTED_TUTOR';
export const SELECTED_INSTITUTE = 'SELECTED_INSTITUTE';
export const UPDATE_COACHING = 'UPDATE_COACHING';
export const UPDATE_TUTORS = 'UPDATE_TUTORS';
export const UPDATE_TUR_INS = 'UPDATE_TUR_INS';

export const UPDATE_APPROVE_TUR_INS = 'UPDATE_APPROVE_TUR_INS';

export const RESET_SELECTED_INSTITUTE = 'RESET_SELECTED_INSTITUTE';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_REQUIREMENTS ='FETCH_REQUIREMENTS';