export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const UPDATE_WORKSHOP = 'UPDATE_WORKSHOP';
export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const EDIT_WORKSHOPS = 'EDIT_WORKSHOPS';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';
export const RESET_SELECTED_WORKSHOP = 'RESET_SELECTED_WORKSHOP';
export const GET_WORKSHOP_PARTICIPANTS = 'GET_WORKSHOP_PARTICIPANTS';
